In [1]:
import atd2022
import torch
import pandas as pd
import numpy as np
from atd_informer import atd_informer
from utils.tools import dotdict
from atd_wrapper import InformerForcaster
pd.set_option('display.max_columns', None)

In [2]:
import importlib
importlib.reload(atd_informer)

In [9]:
args = dotdict()


args.enc_in = 20 # encoder input size
args.dec_in = 20 # decoder input size
args.c_out = 20 # output size
args.factor = 5 # probsparse attn factor
args.d_model = 512 # dimension of model
args.n_heads = 8 # num of heads
args.e_layers = 2 # num of encoder layers
args.d_layers = 1 # num of decoder layers
args.d_ff = 2048 # dimension of fcn in model
args.dropout = 0.05 # dropout
args.attn = 'prob' # attention used in encoder, options:[prob, full]
args.embed = 'timeF' # time features encoding, options:[timeF, fixed, learned]
args.activation = 'gelu' # activation
args.distil = True # whether to use distilling in encoder
args.output_attention = False # whether to output attention in ecoder
args.mix = True
args.padding = 0
args.freq = 'w'
args.inverse=False
args.timeenc=0

args.cols=1
args.checkpoints = "/Users/will/Desktop/tmp"



args.seq_len=5
args.label_len=3
args.pred_len=4


args.batch_size = 1
args.learning_rate = 0.0001
args.loss = 'mse'
args.lradj = 'type1'
args.use_amp = False

args.itr=1
args.train_epochs=2
args.patience=3

In [10]:
informer = atd_informer.ATD_Informer

In [11]:
for ii in range(args.itr):
        # setting record of experiments
    setting = '{}_{}_ft{}_sl{}_ll{}_pl{}_dm{}_nh{}_el{}_dl{}_df{}_at{}_fc{}_eb{}_dt{}_mx{}_{}_{}'.format(args.model, args.data, args.features, 
                args.seq_len, args.label_len, args.pred_len,
                args.d_model, args.n_heads, args.e_layers, args.d_layers, args.d_ff, args.attn, args.factor, args.embed, args.distil, args.mix, args.des, ii)

    # set experiments
    exp = informer(args,t)
    
    # train
    print('>>>>>>>start training : {}>>>>>>>>>>>>>>>>>>>>>>>>>>'.format(setting))
    exp.train(setting)
    
    # test
    print('>>>>>>>testing : {}<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<'.format(setting))
    exp.test(setting)

Use CPU
Use CPU
>>>>>>>start training : None_None_ftNone_sl5_ll3_pl4_dm512_nh8_el2_dl1_df2048_atprob_fc5_ebtimeF_dtTrue_mxTrue_None_0>>>>>>>>>>>>>>>>>>>>>>>>>>
check shapes (193, 20) (193, 20) (193, 2)
check types <class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>
check shapes (17, 20) (17, 20) (17, 2)
check types <class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>
check shapes (15, 20) (15, 20) (15, 2)
check types <class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>
	iters: 100, epoch: 1 | loss: 19.9327240
	speed: 0.0426s/iter; left time: 11.5464s
Epoch: 1 cost time: 7.906923055648804
Epoch: 1, Steps: 185 | Train Loss: 70.0570332 Vali Loss: 15.8859253 Test Loss: 47.7883987
Validation loss decreased (inf --> 15.885925).  Saving model ...
Updating learning rate to 0.0001
	iters: 100, epoch: 2 | loss: 15.8065567
	speed: 0.0802s/iter; left time: 6.8967s
Epoch: 2 cost time: 7.836493253707886
Epoch: 2, Steps: 185 | Train Loss: 63.7807997 Vali Loss: 16.1021042 Test Loss: 44.4966393
EarlyStopping counter: 1 out of 3
Updating learning rate to 5e-05
>>>>>>>testing : None_None_ftNone_sl5_ll3_pl4_dm512_nh8_el2_dl1_df2048_atprob_fc5_ebtimeF_dtTrue_mxTrue_None_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
check shapes (15, 20) (15, 20) (15, 2)
check types <class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>
mse:47.78839874267578, mae:2.6163997650146484

In [33]:
exp.predict()

array([[ 8.1079426e+00,  4.5827322e+00,  7.0564709e+00,  1.7927862e+01,
         4.3815856e+00,  1.6634723e+00,  1.2938401e+00,  1.5130488e+00,
         1.3828031e+00,  1.1751029e-01,  3.3022718e+00,  1.7146778e+00,
         6.2760544e-01,  3.0459225e-01, -9.4327822e-02,  3.7808475e-01,
         2.7038674e+00,  1.1412075e+00,  2.2760725e+00,  1.5633516e-03],
       [ 8.0737514e+00,  4.5192866e+00,  7.0306587e+00,  1.7970146e+01,
         4.4124680e+00,  1.6306219e+00,  1.3158882e+00,  1.4877101e+00,
         1.3696532e+00,  1.2906525e-01,  3.4026375e+00,  1.7586280e+00,
         7.0907515e-01,  2.0888788e-01, -1.2988770e-01,  3.2875338e-01,
         2.8211174e+00,  1.0973167e+00,  2.2448859e+00, -6.0887337e-03],
       [ 8.0212307e+00,  4.5228920e+00,  7.0006189e+00,  1.7996498e+01,
         4.4326525e+00,  1.6598440e+00,  1.3189698e+00,  1.5108910e+00,
         1.3420373e+00,  1.8045482e-01,  3.4022675e+00,  1.7562804e+00,
         7.0972180e-01,  2.2039632e-01, -7.1240902e-02,  3.6375600e-01,
         2.7728658e+00,  1.0396708e+00,  2.2707894e+00, -5.8192715e-02],
       [ 7.9961586e+00,  4.5530658e+00,  7.0267572e+00,  1.7991791e+01,
         4.4205637e+00,  1.6454004e+00,  1.3359904e+00,  1.4774898e+00,
         1.3313562e+00,  1.2511313e-01,  3.3805790e+00,  1.7806784e+00,
         7.2926867e-01,  2.5752723e-01, -4.8929255e-02,  3.4080407e-01,
         2.7165761e+00,  1.0590638e+00,  2.3037548e+00, -6.4733028e-03]],
      dtype=float32)

# Test Model ATD Protocol

In [3]:
truth = atd2022.io.read_csv()

In [4]:
test1=truth["AA"]

In [7]:
test = truth[["AA", "AC"]]

In [8]:
test

Region                 AA                                                      \
Event                  01 02  03  04 05   06 07 08 09 10 11 12 13 14 15 16 17
2013-12-30/2014-01-05   0  0   0   6  0    0  0  0  0  0  0  0  0  0  0  0  0
2014-01-06/2014-01-12   2  0   0  11  0    1  0  0  0  0  0  0  0  0  0  0  0
2014-01-13/2014-01-19   0  1   3   7  1    0  0  0  0  0  1  0  0  0  0  0  0
2014-01-20/2014-01-26   0  1   0   4  0    0  0  2  0  0  0  0  0  0  0  1  0
2014-01-27/2014-02-02   6  1  59   3  0  103  0  4  0  0  0  0  0  0  0  0  0
...                    .. ..  ..  .. ..  ... .. .. .. .. .. .. .. .. .. .. ..
2018-01-08/2018-01-14  13  9  20  85  4    2  0  2  8  0  0  0  0  0  0  1  8
2018-01-15/2018-01-21  14  5   8  10  1    0  0  1  0  1  0  1  0  0  0  0  3
2018-01-22/2018-01-28   5  2   0  23  3    2  5  1  0  0  2  0  0  0  0  3  4
2018-01-29/2018-02-04   3  2   7  37  6   10  4  7  0  1  1  1  0  0  0  0  0
2018-02-05/2018-02-11   7  6   7  49  6    0  1  2  2  2  6  0  1  0  0  0  2

Region                          AC                                           \
Event                 18 19 20  01  02  03   04  05 06  07  08 09 10  11 12
2013-12-30/2014-01-05  0  0  0   4   4   6    9   0  0   1   1  1  0   1  0
2014-01-06/2014-01-12  0  0  0   5   0   8   34   2  1   1   0  0  0   0  2
2014-01-13/2014-01-19  0  1  0   1   0   4    3   0  2   0   0  0  0   0  0
2014-01-20/2014-01-26  0  0  0   3   0   6    1   1  0   0   0  0  0   2  0
2014-01-27/2014-02-02  0  0  0   8   2   2   47   6  4   3   0  0  0   0  2
...                   .. .. ..  ..  ..  ..  ...  .. ..  ..  .. .. ..  .. ..
2018-01-08/2018-01-14  0  0  0  34   9  14  107   3  2   6   3  0  1   8  7
2018-01-15/2018-01-21  0  2  0  36  11  13   67  18  6   7  12  7  5  20  2
2018-01-22/2018-01-28  0  4  0  24  13   9   40  12  9   4   5  1  3  21  5
2018-01-29/2018-02-04  0  0  0  21  13  12   46  17  6  10   6  1  4  17  1
2018-02-05/2018-02-11  0  4  0  32  12  23   64  13  8   7  28  4  4  12  3

Region
Event                  13 14 15 16  17 18  19 20
2013-12-30/2014-01-05   0  0  0  0  11  0   0  0
2014-01-06/2014-01-12   0  0  0  0   4  0   3  0
2014-01-13/2014-01-19   0  0  0  0   1  1   1  0
2014-01-20/2014-01-26   0  0  0  0   0  0   3  0
2014-01-27/2014-02-02   1  0  0  0   3  0   0  0
...                    .. .. .. ..  .. ..  .. ..
2018-01-08/2018-01-14  16  1  0  2   3  0  18  0
2018-01-15/2018-01-21   3  0  0  0   1  0   6  0
2018-01-22/2018-01-28   1  1  0  1   2  0   6  0
2018-01-29/2018-02-04   2  1  0  0   9  0   4  0
2018-02-05/2018-02-11   4  0  0  0  15  0   1  0

[215 rows x 40 columns]

In [5]:
args = dotdict()


args.enc_in = 20 # encoder input size
args.dec_in = 20 # decoder input size
args.c_out = 20 # output size
args.factor = 5 # probsparse attn factor
args.d_model = 1024 # dimension of model
args.n_heads = 12 # num of heads
args.e_layers = 4 # num of encoder layers
args.d_layers = 3 # num of decoder layers
args.d_ff = 2048 # dimension of fcn in model
args.dropout = 0.05 # dropout
args.attn = 'prob' # attention used in encoder, options:[prob, full]
args.embed = 'timeF' # time features encoding, options:[timeF, fixed, learned]
args.activation = 'gelu' # activation
args.distil = True # whether to use distilling in encoder
args.output_attention = False # whether to output attention in ecoder
args.mix = True
args.padding = 0
args.freq = 'w'
args.inverse=False
args.timeenc=0


args.use_gpu=False

#args.cols=1
args.checkpoints = "/Users/will/Desktop/tmp"


"""
args.seq_len=96
args.label_len=48
args.pred_len=1


args.batch_size = 24
args.learning_rate = 0.00001
args.loss = 'mse'
args.lradj = 'type2'
args.use_amp = False

args.itr=2
args.train_epochs=250
args.patience=25
"""

args.seq_len=12
args.label_len=6
args.pred_len=1


args.batch_size = 1
args.learning_rate = 0.0001
args.loss = 'mse'
args.lradj = 'type1'
args.use_amp = False

args.itr=1
args.train_epochs=2
args.patience=3

In [6]:
exp = InformerForcaster(args)

In [7]:
exp.fit(test1)

Use CPU
Use CPU
>>>>>>>start training : None_None_ftNone_sl12_ll6_pl1_dm1024_nh12_el4_dl3_df2048_atprob_fc5_ebtimeF_dtTrue_mxTrue_None_0>>>>>>>>>>>>>>>>>>>>>>>>>>
check shapes (193, 20) (193, 20) (193, 2)
check types <class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>
check shapes (24, 20) (24, 20) (24, 2)
check types <class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>
check shapes (22, 20) (22, 20) (22, 2)
check types <class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>
	iters: 100, epoch: 1 | loss: 24.5679302
	speed: 0.2127s/iter; left time: 55.9350s
Epoch: 1 cost time: 37.491661071777344
Epoch: 1, Steps: 181 | Train Loss: 67.3447022 Vali Loss: 14.5019026 Test Loss: 37.2584839
Validation loss decreased (inf --> 14.501903).  Saving model ...
Updating learning rate to 0.0001
	iters: 100, epoch: 2 | loss: 15.1396847
	speed: 0.3800s/iter; left time: 31.1627s
Epoch: 2 cost time: 37.29013991355896
Epoch: 2, Steps: 181 | Train Loss: 63.9112429 Vali Loss: 16.3089619 Test Loss: 36.0941887
EarlyStopping counter: 1 out of 3
Updating learning rate to 5e-05
1