In [14]:
import atd2022
import torch
import pandas as pd
import numpy as np
from atd_informer import atd_informer
from utils.tools import dotdict
from atd_wrapper import InformerForcaster
pd.set_option('display.max_columns', None)

In [15]:
import importlib
importlib.reload(atd_informer)

In [22]:
args = dotdict()


args.enc_in = 20 # encoder input size
args.dec_in = 20 # decoder input size
args.c_out = 20 # output size
args.factor = 5 # probsparse attn factor
args.d_model = 512 # dimension of model
args.n_heads = 8 # num of heads
args.e_layers = 2 # num of encoder layers
args.d_layers = 1 # num of decoder layers
args.d_ff = 2048 # dimension of fcn in model
args.dropout = 0.05 # dropout
args.attn = 'prob' # attention used in encoder, options:[prob, full]
args.embed = 'timeF' # time features encoding, options:[timeF, fixed, learned]
args.activation = 'gelu' # activation
args.distil = True # whether to use distilling in encoder
args.output_attention = False # whether to output attention in ecoder
args.mix = True
args.padding = 0
args.freq = 'w'
args.inverse=False
args.timeenc=0

args.cols=1
#args.checkpoints = "/Users/will/Desktop/tmp"
args.checkpoints = "/scratch/wzong/atd_tmp"

args.seq_len=12
args.label_len=6
args.pred_len=1


args.batch_size = 1
args.learning_rate = 0.0001
args.loss = 'mse'
args.lradj = 'type2'
args.use_amp = False

args.itr=1
args.train_epochs=2
args.patience=3

In [23]:
informer = atd_informer.ATD_Informer

In [24]:
for ii in range(args.itr):
        # setting record of experiments
    setting = '{}_{}_ft{}_sl{}_ll{}_pl{}_dm{}_nh{}_el{}_dl{}_df{}_at{}_fc{}_eb{}_dt{}_mx{}_{}_{}'.format(args.model, args.data, args.features, 
                args.seq_len, args.label_len, args.pred_len,
                args.d_model, args.n_heads, args.e_layers, args.d_layers, args.d_ff, args.attn, args.factor, args.embed, args.distil, args.mix, args.des, ii)

    # set experiments
    exp = informer(args,test1)
    
    # train
    print('>>>>>>>start training : {}>>>>>>>>>>>>>>>>>>>>>>>>>>'.format(setting))
    exp.train(setting)
    
    # test
    print('>>>>>>>testing : {}<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<'.format(setting))
    exp.test(setting)

Use CPU
Use CPU
>>>>>>>start training : None_None_ftNone_sl12_ll6_pl1_dm512_nh8_el2_dl1_df2048_atprob_fc5_ebtimeF_dtTrue_mxTrue_None_0>>>>>>>>>>>>>>>>>>>>>>>>>>
	iters: 100, epoch: 1 | loss: 37.7525406
	speed: 0.0508s/iter; left time: 13.3624s
Epoch: 1 cost time: 9.142940044403076
Epoch: 1, Steps: 181 | Train Loss: 74.4294736 Vali Loss: 15.0096970 Test Loss: 42.7702408
Validation loss decreased (inf --> 15.009697).  Saving model ...
	iters: 100, epoch: 2 | loss: 25.6982574
	speed: 0.1050s/iter; left time: 8.6137s
Epoch: 2 cost time: 10.977755546569824
Epoch: 2, Steps: 181 | Train Loss: 67.0244692 Vali Loss: 14.2221146 Test Loss: 39.1737595
Validation loss decreased (15.009697 --> 14.222115).  Saving model ...
Updating learning rate to 5e-05
>>>>>>>testing : None_None_ftNone_sl12_ll6_pl1_dm512_nh8_el2_dl1_df2048_atprob_fc5_ebtimeF_dtTrue_mxTrue_None_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
mse:39.17375564575195, mae:2.4755938053131104

In [9]:
exp.predict()

array([ 8.8517685 ,  4.665018  ,  7.035703  , 19.180098  ,  4.7772408 ,
        1.5863205 ,  1.491295  ,  1.7461317 ,  1.4306729 ,  0.3397689 ,
        3.5446384 ,  1.6849699 ,  0.7249474 ,  0.42951158, -0.10027627,
        0.34376797,  2.898783  ,  1.1752076 ,  2.2352297 ,  0.0205084 ],
      dtype=float32)

# Test Model ATD Protocol

In [4]:
truth = atd2022.io.read_csv()

In [5]:
test1=truth["AA"]

In [6]:
test = truth[["AA", "AC"]]

In [7]:
test

Region                 AA                                                      \
Event                  01 02  03  04 05   06 07 08 09 10 11 12 13 14 15 16 17
2013-12-30/2014-01-05   0  0   0   6  0    0  0  0  0  0  0  0  0  0  0  0  0
2014-01-06/2014-01-12   2  0   0  11  0    1  0  0  0  0  0  0  0  0  0  0  0
2014-01-13/2014-01-19   0  1   3   7  1    0  0  0  0  0  1  0  0  0  0  0  0
2014-01-20/2014-01-26   0  1   0   4  0    0  0  2  0  0  0  0  0  0  0  1  0
2014-01-27/2014-02-02   6  1  59   3  0  103  0  4  0  0  0  0  0  0  0  0  0
...                    .. ..  ..  .. ..  ... .. .. .. .. .. .. .. .. .. .. ..
2018-01-08/2018-01-14  13  9  20  85  4    2  0  2  8  0  0  0  0  0  0  1  8
2018-01-15/2018-01-21  14  5   8  10  1    0  0  1  0  1  0  1  0  0  0  0  3
2018-01-22/2018-01-28   5  2   0  23  3    2  5  1  0  0  2  0  0  0  0  3  4
2018-01-29/2018-02-04   3  2   7  37  6   10  4  7  0  1  1  1  0  0  0  0  0
2018-02-05/2018-02-11   7  6   7  49  6    0  1  2  2  2  6  0  1  0  0  0  2

Region                          AC                                           \
Event                 18 19 20  01  02  03   04  05 06  07  08 09 10  11 12
2013-12-30/2014-01-05  0  0  0   4   4   6    9   0  0   1   1  1  0   1  0
2014-01-06/2014-01-12  0  0  0   5   0   8   34   2  1   1   0  0  0   0  2
2014-01-13/2014-01-19  0  1  0   1   0   4    3   0  2   0   0  0  0   0  0
2014-01-20/2014-01-26  0  0  0   3   0   6    1   1  0   0   0  0  0   2  0
2014-01-27/2014-02-02  0  0  0   8   2   2   47   6  4   3   0  0  0   0  2
...                   .. .. ..  ..  ..  ..  ...  .. ..  ..  .. .. ..  .. ..
2018-01-08/2018-01-14  0  0  0  34   9  14  107   3  2   6   3  0  1   8  7
2018-01-15/2018-01-21  0  2  0  36  11  13   67  18  6   7  12  7  5  20  2
2018-01-22/2018-01-28  0  4  0  24  13   9   40  12  9   4   5  1  3  21  5
2018-01-29/2018-02-04  0  0  0  21  13  12   46  17  6  10   6  1  4  17  1
2018-02-05/2018-02-11  0  4  0  32  12  23   64  13  8   7  28  4  4  12  3

Region
Event                  13 14 15 16  17 18  19 20
2013-12-30/2014-01-05   0  0  0  0  11  0   0  0
2014-01-06/2014-01-12   0  0  0  0   4  0   3  0
2014-01-13/2014-01-19   0  0  0  0   1  1   1  0
2014-01-20/2014-01-26   0  0  0  0   0  0   3  0
2014-01-27/2014-02-02   1  0  0  0   3  0   0  0
...                    .. .. .. ..  .. ..  .. ..
2018-01-08/2018-01-14  16  1  0  2   3  0  18  0
2018-01-15/2018-01-21   3  0  0  0   1  0   6  0
2018-01-22/2018-01-28   1  1  0  1   2  0   6  0
2018-01-29/2018-02-04   2  1  0  0   9  0   4  0
2018-02-05/2018-02-11   4  0  0  0  15  0   1  0

[215 rows x 40 columns]

In [11]:
args = dotdict()


args.enc_in = 20 # encoder input size
args.dec_in = 20 # decoder input size
args.c_out = 20 # output size
args.factor = 5 # probsparse attn factor
args.d_model = 1024 # dimension of model
args.n_heads = 12 # num of heads
args.e_layers = 4 # num of encoder layers
args.d_layers = 3 # num of decoder layers
args.d_ff = 2048 # dimension of fcn in model
args.dropout = 0.05 # dropout
args.attn = 'prob' # attention used in encoder, options:[prob, full]
args.embed = 'timeF' # time features encoding, options:[timeF, fixed, learned]
args.activation = 'gelu' # activation
args.distil = True # whether to use distilling in encoder
args.output_attention = False # whether to output attention in ecoder
args.mix = True
args.padding = 0
args.freq = 'w'
args.inverse=False
args.timeenc=0


args.use_gpu=True

#args.cols=1
#args.checkpoints = "/Users/will/Desktop/tmp"
args.checkpoints = "/scratch/wzong/atd_tmp"

"""
args.seq_len=96
args.label_len=48
args.pred_len=1


args.batch_size = 24
args.learning_rate = 0.00001
args.loss = 'mse'
args.lradj = 'type2'
args.use_amp = False

args.itr=2
args.train_epochs=250
args.patience=25
"""

args.seq_len=50
args.label_len=6
args.pred_len=1


args.batch_size = 1
args.learning_rate = 0.0001
args.loss = 'mse'
args.lradj = 'type1'
args.use_amp = False

args.itr=1
args.train_epochs=2
args.patience=3

In [12]:
exp = InformerForcaster(args)

In [13]:
exp.fit(test)

got here
Use GPU: cuda:None
Use GPU: cuda:None
>>>>>>>start training : None_None_ftNone_sl50_ll6_pl1_dm1024_nh12_el4_dl3_df2048_atprob_fc5_ebtimeF_dtTrue_mxTrue_None_0>>>>>>>>>>>>>>>>>>>>>>>>>>
	iters: 100, epoch: 1 | loss: 7.6871476
	speed: 0.0783s/iter; left time: 14.6493s
Epoch: 1 cost time: 11.237469673156738
Epoch: 1, Steps: 143 | Train Loss: 58.8098357 Vali Loss: 14.1456537 Test Loss: 37.7031937
Validation loss decreased (inf --> 14.145654).  Saving model ...
Updating learning rate to 0.0001
	iters: 100, epoch: 2 | loss: 5.7605562
	speed: 0.1238s/iter; left time: 5.4485s
Epoch: 2 cost time: 11.343801975250244
Epoch: 2, Steps: 143 | Train Loss: 53.2055416 Vali Loss: 15.9148293 Test Loss: 36.4517441
EarlyStopping counter: 1 out of 3
Updating learning rate to 5e-05
0
got here
Use GPU: cuda:None
Use GPU: cuda:None
>>>>>>>start training : None_None_ftNone_sl50_ll6_pl1_dm1024_nh12_el4_dl3_df2048_atprob_fc5_ebtimeF_dtTrue_mxTrue_None_0>>>>>>>>>>>>>>>>>>>>>>>>>>
	iters: 100, epoch: 1 | loss: 318.1614380
	speed: 0.0751s/iter; left time: 14.0492s
Epoch: 1 cost time: 10.928643941879272
Epoch: 1, Steps: 143 | Train Loss: 427.0137521 Vali Loss: 585.6093140 Test Loss: 124.8465729
Validation loss decreased (inf --> 585.609314).  Saving model ...
Updating learning rate to 0.0001
	iters: 100, epoch: 2 | loss: 272.4662781
	speed: 0.1296s/iter; left time: 5.7023s
Epoch: 2 cost time: 11.166817665100098
Epoch: 2, Steps: 143 | Train Loss: 355.8020642 Vali Loss: 499.0832825 Test Loss: 88.6406479
Validation loss decreased (585.609314 --> 499.083282).  Saving model ...
Updating learning rate to 5e-05
1

In [3]:
torch.cuda.is_available()

True

In [25]:
exp.predict()

array([ 8.557855  ,  4.787674  ,  6.99029   , 19.201435  ,  4.8234425 ,
        1.7256876 ,  1.5662795 ,  2.2666464 ,  1.3909669 ,  0.21106915,
        3.6273484 ,  1.7174969 ,  0.6368366 ,  0.30843312, -0.0468483 ,
        0.31663918,  2.97511   ,  1.1269442 ,  2.1073618 , -0.06266728],
      dtype=float32)